//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace patient_appointment.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class appointment_schedule
    {
        public int appointmentID { get; set; }
        public string patient_name { get; set; }
        public string email { get; set; }
        public string phone_number { get; set; }
        public string doctor_name { get; set; }
        public System.DateTime date_and_time { get; set; }
        public string reference_no { get; set; }
        public int total_charge { get; set; }
        public string service { get; set; }
        public string appointment_status { get; set; }
        public string message { get; set; }
    }
}
