//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace patient_appointment.DBModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int userID { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string gender { get; set; }
        public System.DateTime birthdate { get; set; }
        public string phone_number { get; set; }
        public System.DateTime date_created { get; set; }
        public string user_photo { get; set; }
        public string password { get; set; }
        public string password_salt { get; set; }
    }
}
